/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface _Migrations {
  applied_at: Generated<Timestamp>;
  applied_by: Generated<string>;
  checksum: string | null;
  description: string | null;
  error_log: string | null;
  execution_time_ms: number | null;
  id: Generated<number>;
  migration_name: string;
  output_log: string | null;
  status: string | null;
}

export interface DailyFeedingSummary {
  daily_food_goal_grams: number | null;
  feeding_date: Timestamp | null;
  goal_achievement_pct: Numeric | null;
  goal_status: string | null;
  met_target: boolean | null;
  over_target: boolean | null;
  pet_id: string | null;
  pet_name: string | null;
  total_eaten_grams: Int8 | null;
  total_leftover_grams: Int8 | null;
  total_meals: Int8 | null;
  total_served_grams: Int8 | null;
  under_target: boolean | null;
}

export interface Feedings {
  amount_eaten_grams: number;
  /**
   * Calculado automáticamente: servido - comido
   */
  amount_leftover_grams: Generated<number | null>;
  amount_served_grams: number;
  /**
   * Calificación del apetito: refused (rechazó), poor (pobre), normal, good (bueno), excellent (excelente)
   */
  appetite_rating: string | null;
  created_at: Generated<Timestamp>;
  /**
   * Velocidad al comer: very_slow (muy lento), slow (lento), normal, fast (rápido), very_fast (muy rápido)
   */
  eating_speed: string | null;
  feeding_date: Generated<Timestamp>;
  feeding_time: string | null;
  food_id: string;
  had_diarrhea: Generated<boolean>;
  /**
   * Registro de si defecó tras esta toma (ayuda a detectar problemas digestivos)
   */
  had_stool: Generated<boolean>;
  household_id: string;
  id: Generated<string>;
  notes: string | null;
  pet_id: string;
  /**
   * Número de ración del día en que se registró esta alimentación
   */
  portion_number: number | null;
  recorded_by: string;
  stool_quality: string | null;
  updated_at: Generated<Timestamp>;
  vomited: Generated<boolean>;
}

export interface Foods {
  age_range: string | null;
  brand: string | null;
  /**
   * Calorías por cada 100 gramos de alimento
   */
  calories_per_100g: Numeric | null;
  carbs_percentage: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  digestibility: string | null;
  fat_percentage: Numeric | null;
  fiber_percentage: Numeric | null;
  /**
   * Tipo: dry (pienso), wet (húmeda), raw (BARF), homemade, treat, supplement
   */
  food_type: string;
  household_id: string;
  id: Generated<string>;
  ingredients: string | null;
  is_active: Generated<boolean>;
  moisture_percentage: Numeric | null;
  name: string;
  notes: string | null;
  package_size_grams: number | null;
  palatability: string | null;
  /**
   * Foto del producto: emoji, imagen base64 o URL externa
   */
  photo_url: string | null;
  price_per_package: Numeric | null;
  product_image_url: string | null;
  /**
   * Porcentaje de proteína sobre materia seca
   */
  protein_percentage: Numeric | null;
  /**
   * URL de compra online del producto (e.g., Amazon, Tiendanimal)
   */
  purchase_url: string | null;
  serving_size_grams: number | null;
  /**
   * Array de especies para las que es apto el alimento
   */
  suitable_for_species: Generated<string[] | null>;
  updated_at: Generated<Timestamp>;
}

export interface HouseholdMembers {
  household_id: string;
  joined_at: Generated<Timestamp>;
  profile_id: string;
  /**
   * Rol: owner (administrador) o member (miembro)
   */
  role: string;
}

export interface Households {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface PetPortionSchedules {
  created_at: Generated<Timestamp>;
  /**
   * Cantidad esperada de gramos para esta toma específica. Opcional: si NULL, se calcula como daily_food_goal_grams / daily_meals_target.
   */
  expected_grams: number | null;
  id: Generated<string>;
  notes: string | null;
  pet_id: string;
  /**
   * Número de ración del día (1, 2, 3...)
   */
  portion_number: number;
  /**
   * Hora programada para esta toma (ej: 08:00, 14:00, 20:00). Usado para calcular puntualidad y alertas.
   */
  scheduled_time: string;
  updated_at: Generated<Timestamp>;
}

export interface Pets {
  activity_level: string | null;
  allergies: string[] | null;
  appetite: string | null;
  birth_date: Timestamp | null;
  /**
   * Condición corporal: underweight, ideal, overweight, obese
   */
  body_condition: string | null;
  breed: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  /**
   * Meta diaria de alimento en gramos (suma de todas las raciones)
   */
  daily_food_goal_grams: Generated<number>;
  /**
   * Número objetivo de raciones diarias
   */
  daily_portions_target: Generated<number | null>;
  gender: string | null;
  health_notes: string | null;
  household_id: string;
  id: Generated<string>;
  /**
   * false = mascota fallecida o dada en adopción
   */
  is_active: Generated<boolean>;
  medications: string[] | null;
  name: string;
  photo_url: string | null;
  species: string;
  updated_at: Generated<Timestamp>;
  weight_kg: Numeric | null;
}

export interface Profiles {
  /**
   * ID de proveedor OAuth (Google)
   */
  auth_id: string;
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  email: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  _migrations: _Migrations;
  daily_feeding_summary: DailyFeedingSummary;
  feedings: Feedings;
  foods: Foods;
  household_members: HouseholdMembers;
  households: Households;
  pet_portion_schedules: PetPortionSchedules;
  pets: Pets;
  profiles: Profiles;
}
